name: Build yt-dlp extracts

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *" # раз в 6 часов

concurrency:
  group: ytdlp-extracts
  cancel-in-progress: false

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Get latest yt-dlp release tag
        id: get_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(gh api repos/yt-dlp/yt-dlp/releases/latest --jq .tag_name)
          echo "YTDLP_TAG=$TAG" >> $GITHUB_ENV
          echo "Latest yt-dlp release: $TAG"

      - name: Checkout yt-dlp at the release tag
        uses: actions/checkout@v4
        with:
          repository: yt-dlp/yt-dlp
          ref: ${{ env.YTDLP_TAG }}
          path: vendor/yt-dlp
          fetch-depth: 1

      - name: Extract _VALID_URL, _EMBED_REGEX and test urls
        run: |
          python - <<'PY'
          import sys, importlib, inspect, re
          from pathlib import Path

          root = Path('vendor/yt-dlp')
          sys.path.insert(0, str(root))

          regexes = set()
          embed_regexes = set()
          urls = set()

          from yt_dlp.extractor.common import InfoExtractor
          extractor_dir = root / 'yt_dlp' / 'extractor'

          Pattern = getattr(re, "Pattern", type(re.compile("")))

          def add_regex(val, dest):
            if not val:
              return
            if isinstance(val, str):
              dest.add(val)
            elif isinstance(val, Pattern):
              dest.add(val.pattern)
            elif isinstance(val, (list, tuple, set)):
              for v in val:
                add_regex(v, dest)

          for p in extractor_dir.glob('*.py'):
            if p.name in ('__init__.py', '_extractors.py'):
              continue
            modname = f"yt_dlp.extractor.{p.stem}"
            try:
              m = importlib.import_module(modname)
            except Exception as e:
              print(f"[WARN] skip {modname}: {e}")
              continue

            for name, obj in m.__dict__.items():
              if inspect.isclass(obj) and issubclass(obj, InfoExtractor) and obj is not InfoExtractor:
                add_regex(getattr(obj, '_VALID_URL', None), regexes)
                add_regex(getattr(obj, '_EMBED_REGEX', None), embed_regexes)

                tests = []
                _tests = getattr(obj, '_TESTS', None)
                if isinstance(_tests, (list, tuple)):
                  tests.extend(_tests)
                _test = getattr(obj, '_TEST', None)
                if isinstance(_test, dict):
                  tests.append(_test)

                for t in tests:
                  if isinstance(t, dict):
                    u = t.get('url')
                    if isinstance(u, str) and u:
                      urls.add(u)

          Path('artifacts').mkdir(exist_ok=True)

          def write_sorted(name, data):
            with open(f'artifacts/{name}', 'w', encoding='utf-8') as f:
              for s in sorted(data):
                f.write(s + '\n')

          write_sorted('valid_url_regexes.txt', regexes)
          write_sorted('embed_regexes.txt', embed_regexes)
          write_sorted('test_urls.txt', urls)

          print(f"Wrote {len(regexes)} _VALID_URL, {len(embed_regexes)} _EMBED_REGEX and {len(urls)} test urls")
          PY

      - name: Publish to single tag/release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="ytdlp-extracts"
          TITLE="yt-dlp _VALID_URL, _EMBED_REGEX and test urls"
          NOTES="Auto-updated from yt-dlp ${YTDLP_TAG}"
          gh release view "$TAG" >/dev/null 2>&1 || gh release create "$TAG" --title "$TITLE" --notes "$NOTES"
          gh release upload "$TAG" \
            artifacts/valid_url_regexes.txt \
            artifacts/embed_regexes.txt \
            artifacts/test_urls.txt \
            --clobber
